name: CI/CD Teamed-app

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$HOSTNAME '
            # Capture the hostname
            myhostname=$(hostname)
            echo "The hostname of this machine is: $myhostname"
            
            sudo su
            cd /home/teamed-app-bk/teamedapp-api/ && sudo git pull
            yarn && sudo systemctl restart teamed-bk.service && sudo systemctl status teamed-bk.service
           
           
          ' 
